doc/UNT0012.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/UnityAnalyzerVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/UnusedCoroutineReturnValueTests.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs

Fixes #12.
Adds an analyzer to detect and fix direct calls to coroutines, where their return value is unused. Such calls will not be executed.
Provides a code fix that wraps the call to a coroutine in StartCoroutine().

Unused coroutine return value analyzer

---

doc/index.md
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #11 
Adds support for SerializeReference to our existing SerializeField suppressor
- Change `SerializeFieldSuppressor` to support the new `SerializeReference` attribute
- Adjust relevant docs and strings
Our suppressors currently fail to suppress CS0649. It's not clear if this ever worked for SerializeField. I've filed #15 to fix whatever the underlying issue is, which should light up CS0649 suppression in this case as well.

Add support for SerializeReference

---

README.md
src/Microsoft.Unity.Analyzers.Mpack.sln
src/Microsoft.Unity.Analyzers.Mpack/AddinInfo.cs
src/Microsoft.Unity.Analyzers.Mpack/Manifest.addin.xml
src/Microsoft.Unity.Analyzers.Mpack/Microsoft.Unity.Analyzers.Mpack.csproj
src/Microsoft.Unity.Analyzers.Vsix.sln
src/Microsoft.Unity.Analyzers.sln

Fixes #20.
This adds an mpack project to the solution. On Visual Studio for Mac, make this project the startup project and click run to launch an experimental instance of Visual Studio for Mac where the Unity analyzers will be loaded to debug them.

Add an mpack project to develop and debug analyzers on VSM

---

src/Microsoft.Unity.Analyzers.Tests/EmptyUnityMessageTests.cs
src/Microsoft.Unity.Analyzers/EmptyUnityMessage.cs

Fixes #25 
Polymorphic modifiers like virtual, override or abstract added by users give those methods another semantic that we can't discover, we should not provide a diagnostic here.

Do not report UNT0001 on methods with modifiers

---

src/Microsoft.Unity.Analyzers.Tests/MessageSignatureTests.cs
src/Microsoft.Unity.Analyzers/ScriptInfo.cs

Fixes #27 
Unity is able to call Unity messages by Reflection, even if not all parameters are provided. For example you can use `OnAnimatorIK()` or `OnAnimatorIK(int layerIndex)` in your code, and both of those methods work perfectly fine. 
- Update the ScriptInfo class to adopt the same logic for detection of valid Unity messages. 
- Add extra tests for `UNT0006`

Adopt the same Unity logic for Unity message detection

---

doc/UNT0013.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/ImproperSerializeFieldTests.cs
src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes #14
This PR adds an analyzer that warns about improper uses of the `SerializeField` attribute. It also provides a code fix suggestion to automatically remove improper uses of the attribute from the code.
I'm not sure if my solution for checking fields is correct. Field declarations can include multiple symbols. In this case, I iterate through the symbols, and any that meet the requirements results in the warning and code fix suggestion. Could use another set of eyes on it - does this look correct to you?

ImproperSerializeField analyzer

---

doc/UNT0005.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/UpdateDeltaTimeTests.cs
src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs

Fixes #26 
Retire UNT0005
Set the rule descriptor `IsEnabledByDefault` to `false`, so the rule will not be active by default anymore, until explicitly enabled using an `.editorconfig` or `ruleset` file.

Retire UNT0005

---

doc/UNT0014.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/GetComponentIncorrectTypeTests.cs
src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes #16
Adds an analyzer that detects if the user is passing a type to `GetComponent` that is not a Unity Component or Interface type

GetComponentIncorrectTypeAnalyzer

---

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers.Tests/UnusedMessageSuppressorTests.cs
src/nuget.config

The IDE analyzers currently have strong dependencies on Visual Studio components, so several analyzers are not executing outside of Visual Studio. We are currently mocking them in our tests.
IDE0060 was ported to a new nuget package, so we can use it, instead of mocking it.
Import the Microsoft.CodeAnalysis.CSharp.CodeStyle nuget package.
Given this package content is tagged as 'analyzer' (and all types are internal), nothing is copied to the output folder. But for our use-case, we need this copy in order to properly load the assembly in our test infrastructure.
I'm using `$(NugetPackageRoot)` to manually reference assemblies.
I tried using:
```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="3.6.0-2.20164.4" GeneratePathProperty="true" />`
```
and 
```xml …
```

Un-mock IDE0060

---

src/Microsoft.Unity.Analyzers.Tests/BaseTest.cs
src/Microsoft.Unity.Analyzers.Tests/ContextMenuSuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/ImproperSerializeFieldTests.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/SerializeFieldSuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/TagComparisonTests.cs
src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingTests.cs
src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs

Expose all diagnostics to the test infrastructure
Given we now expose all messages, we have to refine several tests, as they are executed in full isolation (no suppressors when testing a regular analyzer/codefix for instance). In extenso, leaving an unused namespace will mark the test as failed.

Expose all diagnostics to the test infrastructure

---

.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Bump Unity to the latest LTS
Bump URLs and salt the cache key with the unity version (to prevent unexpected cache issues)

Bump Unity to 2018.4.19f1 and salt cache key with unity version

---

doc/USP0012.md
src/Microsoft.Unity.Analyzers.Tests/InitializeOnLoadMethodSuppressorTests.cs
src/Microsoft.Unity.Analyzers/InitializeOnLoadMethodSuppressor.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #58 
Fixed reporting IDE0051 for methods decorated with `InitializeOnLoadMethodAttribute` and `RuntimeInitializeOnLoadMethodAttribute` (InitializeOnLoad_Method_Attribute != InitializeOnLoadAttribute )
Added a new dedicated suppressor

Add InitializeOnLoadMethodAttribute suppressor

---

.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Consistency tests (for suppressor/analyzer ids) are not useful when we have multiple PR waiting for validation.
Let's run them only on the master branch.

Disable consistency tests for feature branches

---

README.md
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj

Bump Roslyn-related assemblies to 3.4 (compatible with VS 16.4, VSM 8.4)

Bump baseline to 16.4/8.4/Roslyn 3.4

---

doc/UNT0009.md
doc/UNT0015.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/InitializeOnLoadMethodTests.cs
src/Microsoft.Unity.Analyzers/InitializeOnLoadMethod.cs
src/Microsoft.Unity.Analyzers/InitializeOnLoadMethodSuppressor.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes #29 
Checks for valid method signature when decorated with `InitializeOnLoadMethodAttribute` or `RuntimeInitializeOnLoadMethod` attributes.
Discussed in #50:
> In the end, I think it's better to create a new analyzer/codefix.
> 
> The current analyzer is working with `InitializeOnLoadAttribute`, working at a **type** level. When a static ctor is not here, the 'fix' is to **create one**.
> 
> `InitializeOnLoadMethodAttribute` and `RuntimeInitializeOnLoadMethod` are working on a **method** level. When the method signature/modifiers are incorrect, the 'fix' is to **correct** the method signature/modifiers in-place.
> 
> So even if the work seems quite similar, the analysis and the fix are different for both cases.
> 
> So I'm closing this and going to create a new PR.
> 
I also updated …

Add InitializeOnLoadMethod analyzer

---

doc/UNT0016.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/MethodInvocationDirectCallTests.cs
src/Microsoft.Unity.Analyzers.Tests/MethodInvocationNameOfTests.cs
src/Microsoft.Unity.Analyzers.Tests/MethodInvocationTests.cs
src/Microsoft.Unity.Analyzers.Tests/UnusedMethodSuppressorTests.cs
src/Microsoft.Unity.Analyzers/MethodInvocation.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs

Fixes #37 and #65
Using `Invoke`, `InvokeRepeating`, `StartCoroutine` or `StopCoroutine` with a first argument being a string literal is not type safe. Instead it's recommanded to use the `nameof` operator or a direct call for coroutines. The further benefit of doing this is the ability for the method to use a rename refactoring without remembering to update the string literals.
Added one diagnostic and two code fixes.
Note that `ConsistencyTests` will fail because of the analyzer ID. That's expected while all other PRs are not yet merged.

Method invocation analyzer

---

src/Microsoft.Unity.Analyzers.Tests/GetComponentIncorrectTypeTests.cs
src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs

GetComponent<T> allows to use generic type parameters, which derived from Component
In that case "GetComponent called with non-Component"  should not be triggered
Fixes #71
UNT0014 triggers in cases with generic type parameters (with Component constraint), which is correct, that PR resolves this problem.
- GetComponentIncorrectTypeAnalyzer now checks generic type parameters constraints and do not raise a warning if Component type constraint is found - https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs
- Additional tests here - https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/src/Microsoft.Unity.Analyzers.Tests/GetComponentIncorrectTypeTests.cs, that covers such cases

Check generic type parameters in UNT0014 diagnostic

---

doc/USP0013.md
doc/USP0014.md
doc/USP0015.md
doc/index.md
src/.editorconfig
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/MessageFxCopSuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/MessageSuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers.Tests/SerializeFieldFxCopSuppressorTests.cs
src/Microsoft.Unity.Analyzers/MessageSuppressor.cs
src/Microsoft.Unity.Analyzers/MethodInvocation.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs

Fixes #81 
Suppress additionnal rules for FxCop analyzers:
- `CA1801`: Remove the parameter or use it in the method body.
- `CA1822`: Mark members as static.
- `CA1823`: Remove unused fields.
Reuse existing detection mechanisms for MonoBehaviours/Messages/Serialized fields

Add fxcop suppressions

---

doc/USP0009.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/ContextMenuSuppressorTests.cs
src/Microsoft.Unity.Analyzers/ContextMenuSuppressor.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #84 
Suppress IDE0051 for methods decorated with `MenuItem` attribute.
Update the `ContextMenuSuppressor` rule `USP0009` to detect both `ContextMenu` and `MenuItem` attributes.

Add MenuItem to the ContextMenuSuppressor

---

src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs
src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs

Fixes #88 
- Fix parentheses handling for both [USP0001](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/USP0001.md) and [USP0002](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/master/doc/USP0002.md)
- Fix detection when the conditional expression is passed as an argument

Fix USP0001 and USP0002 not working with extra parentheses or method arguments

---

src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes #93
Typo in the `InitializeOnLoadStaticCtorDiagnosticMessageFormat` resource entry.

Fixes #93, typo with InitializeOnLoadStaticCtorDiagnosticMessageFormat

---

src/Microsoft.Unity.Analyzers.Tests/MessageSuppressorTests.cs
src/Microsoft.Unity.Analyzers/ScriptInfo.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #85 
Add AssetPostprocessor members to the list of well known messages, so we can benefit from all the related suppressors.

Add AssetPostprocessor members to the list of known messages

---

doc/USP0016.md
src/Microsoft.Unity.Analyzers.Tests/NullableReferenceTypesSuppressorTests.cs
src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes [#99](https://github.com/microsoft/Microsoft.Unity.Analyzers/issues/99)
Suppresses CS8618 warnings for fields and properties that inherit UnityEngine.Object and are assigned to in Unity's initialization methods or the inspector.

Nullable reference types suppressor

---

.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Bump Unity version to 2019.4.8f1 LTS, used by the test infrastructure

Bump Unity version to 2019.4.8f1 LTS

---

doc/UNT0010.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/CreateInstanceTests.cs
src/Microsoft.Unity.Analyzers/CreateInstance.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes #108 
Extend the existing rule to handle all components and not only MonoBehaviours. Interestingly, the code was already very oriented around the component concept.

Extend UNT0010 to all components

---

src/.editorconfig
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj
src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs

Bump all infrastructure packages (test tools and SDK, analyzers) to the latest stable version.
We do not bump the Roslyn version, so no changes regarding VS compatibility.
- Fixed RS1030 analyzer issue (get the semantic model from the diagnostic context and not from the compilation)
- Disabled RS2008 analyzer issue (we already track analyzer/suppressor IDs on our side)

Package upgrade

---

src/Microsoft.Unity.Analyzers/Reflection.cs
src/Microsoft.Unity.Analyzers/TypeSymbolExtensions.cs

Fixes #124 
We could hit NRE on `ToDisplayString()` given `ISymbol.ContainingNamespace` might be null.

Fix NREs with ISymbol.ContainingNamespace

---

src/new-analyzer/new-analyzer.csproj

Fixes a build warning on .NET Core 5.

Target .net core 3.1 LTS for the new-analyzer project

---

src/Microsoft.Unity.Analyzers.Tests/ContextMenuSuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/UnusedMethodSuppressorTests.cs
src/Microsoft.Unity.Analyzers/ContextMenuSuppressor.cs

Fixes #127
-Using [UnityEditor.MenuItem] causes "Private member is unused"

Resolved: Using [UnityEditor.MenuItem] causes "Private member is unused"

---

src/Microsoft.Unity.Analyzers.Tests/Directory.Build.props
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers.Tests/NullableReferenceTypesSuppressorTests.cs
src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj
src/nuget.config

Bump packages to the latest versions.
Note that we only bump Roslyn on the test side, Our analyzers are still targeting 3.4.0.
I reverted the EditorConfig filtering, as I was not able to make it work with a newer Roslyn (we are now filtering in code)...
In the near future, we'll have to migrate from FxCop analyzers to .NET analyzers. (but all diagnostics are not there yet).
See https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019

Bump packages

---

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/UpdateDeltaTimeTests.cs

Previously, when adding analyzer-rules using a descriptor with `IsEnabledByDefault = false`, analyzer testing was not possible.

Force tested analyzers to be enabled (even when IsEnabledByDefault is false)

---

src/Microsoft.Unity.Analyzers.Tests/SetPositionAndRotationTests.cs
src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs

@shreyalpandit 
I refactored your analyzer/codefix by extracting the following duplicate code into a method:
```
if (assignmentExpression.FirstAncestorOrSelf<BlockSyntax>() == null)
return document;
if (assignmentExpression.FirstAncestorOrSelf<ExpressionStatementSyntax>() == null)
return document;
var siblingsAndSelf = block.ChildNodes().ToImmutableArray();
var block = assignmentExpression.FirstAncestorOrSelf<BlockSyntax>();
var expression = assignmentExpression.FirstAncestorOrSelf<ExpressionStatementSyntax>();
var lastIndexOf = siblingsAndSelf.LastIndexOf(expression);
if (lastIndexOf == -1)
return document;
var nextIndex = lastIndexOf + 1;
if (nextIndex == siblingsAndSelf.Length)
return document;
var statement = siblingsAndSelf[nextIndex];
if (!(statement is ExpressionStatementSyntax …
```

Refactor SetPositionAndRotationAnalyzer

---

src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs
src/Microsoft.Unity.Analyzers/InvocationExpressionSyntaxExtensions.cs
src/Microsoft.Unity.Analyzers/KnownMethods.cs
src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs
src/Microsoft.Unity.Analyzers/TagComparison.cs
src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs

`GetSymbolInfo` is pretty costly. We found cases of projects where we'd spend an enormous amount of time in there, depending on the code patterns.
We need to do as much work as possible to filter the patterns we want to provide a diagnostic for before calling GetSymbolInfo.

Avoid calling GetSymbolInfo until we need to

---

.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Bump Unity to 2020.3.24f1

---

src/Microsoft.Unity.Analyzers.Tests/NullableReferenceTypesSuppressorTests.cs
src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs

Fixes #197 
Remove `UnityEngine.Object` type checking 
- See the related issue for extra context
- Adding repro as new test

Fix USP0016 for non unity objects

---

.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Bump Unity to 2020.3.28f1 LTS

---

.github/workflows/ci-windows.yml

Seems that github recently migrated windows images. But CodeQL is not compatible yet.

Tracing builds with CodeQL is currently not supported on Windows 11 and Windows Server 2022.

---

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs

Fixes #207 
Always reference netstandard facades
Tested with:
- 2020.3.26f1 LTS
- 2021.2.13f1
- 2022.1.0b9 (mandatory in this case)

Always reference netstandard facades

---

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticResult.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/MessageCodeQualitySuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers.Tests/SerializeFieldCodeQualitySuppressorTests.cs
src/Microsoft.Unity.Analyzers.Tests/UnityPath.cs
src/Microsoft.Unity.Analyzers/MessageSuppressor.cs
src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj
src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs

Bump package versions and use `Microsoft.CodeAnalysis.NetAnalyzers` instead of the now deprecated `Microsoft.CodeQuality.Analyzers`. Fix new warnings.
See the guidance here:
https://github.com/dotnet/roslyn-analyzers#main-analyzers

Bump packages and move to NetAnalyzers

---

doc/USP0001.md
doc/USP0002.md
doc/USP0015.md
doc/USP0016.md
doc/USP0017.md
doc/USP0018.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/ThrowExpressionSuppressorTests.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/ThrowExpressionSuppressor.cs
src/new-analyzer/SuppressorDiagnosticBuilder.cs

Fixes #204 
Add a new `USP0018` suppressor for throw expressions on types extending `UnityEngine.Object`.
- Added suppressor and documentation
- Fixed the default suppressor template always using `UnusedMethodSuppressor` instead of the newly created suppressor. 
- Fixed non-catched exceptions in tests, regarding missing analyzer options. (needed here for `csharp_style_throw_expression`)

Add `USP0018`, ThrowExpressionSuppressor

---

.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Bump Unity to 2021.3.1f1 LTS

---

doc/UNT0028.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/PhysicsAllocMethodUsageTests.cs
src/Microsoft.Unity.Analyzers/MethodUsage.cs
src/Microsoft.Unity.Analyzers/PhysicsAllocMethodUsage.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Add an analyzer for flagging allocating APIs.  See https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity7.html
We only added support for `Physics` and not `Physics2D`. It seems that `Physics2D` non-alloc methods will be deprecated in a future build and it is recommended to use simpler API instead. See https://docs.unity3d.com/ScriptReference/Physics2D.BoxCastNonAlloc.html

Add UNT0028 - Use non-allocating physics APIs

---

src/Microsoft.Unity.Analyzers.Tests/MessageSignatureTests.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #237
Add OnPostprocessAllAssets overload to prevent incorrect UNT0006

Add OnPostprocessAllAssets overload to prevent incorrect UNT0006

---

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/UnityPath.cs

Fixes #264 
Users should be able to run unit tests on linux. The test is that any test runs on linux at all so no new test is necessary.
* Check for linux installations in $HOME/Unity/Hub
* Fix System.dll is actully capitalized and file systems on linux default to case sensitive
* Tested on Ubuntu 22.10

Detect unity installations on linux

---

src/Directory.Packages.props
src/Microsoft.Unity.Analyzers.Tests/BaseTest.cs
src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
src/Microsoft.Unity.Analyzers.Tests/SetLocalPositionAndRotationTests.cs
src/Microsoft.Unity.Analyzers/BaseSetPositionAndRotation.cs

Fixes #263 
Add skippable facts support to conditionally ignore tests.
Example with 2021.3.9f1 (`Transform.SetLocalPositionAndRotation` was added in 2021.3.11f1)
This is only useful when full analyzer compilation is not needed. For other advanced usages we have `AnalyzerVerificationContext` to filter given options, ids or LanguageVersion (that we use for suppressor tests).

Skippable facts

---

src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingTests.cs

Ignore CS0618 for `CantFixNullPropagationSideEffect`. Obsolete attribute was introduced with Unity 2023.1.

Ignore CS0618 for `CantFixNullPropagationSideEffect`

---

doc/UNT0022.md
doc/UNT0032.md
src/Microsoft.Unity.Analyzers.Tests/SetLocalPositionAndRotationTests.cs
src/Microsoft.Unity.Analyzers.Tests/SetPositionAndRotationTests.cs
src/Microsoft.Unity.Analyzers/BasePositionAndRotation.cs
src/Microsoft.Unity.Analyzers/SetLocalPositionAndRotation.cs
src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Add support for `TransformAccess`  #257.
Add initial refactoring needed to support `Get*` functions.
It will be a bit more complicated for `Get*` because we'll have to support `VariableDeclarationSyntax` in addition of `AssignmentExpressionSyntax`. Like for:
```csharp
var foo = transform.position;
existing = transform.location;
=>
transform.GetPositionAndRotation(out var foo, out existing);
```
And we have to check that the argument passed as an `out/ref` is compatible. (like it is not a property).

Add support for TransformAccess in UNT0032 and UNT0022

---

src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs

Fix an `ArgumentOutOfRangeException` when using partial types with `UNT0008`.
We were using the diagnostic' `SourceTree` instead of the specific method location' `SourceTree` (which is the same of course for non-partial types).
I also audited all other `FindNode` usages, we should be good.

Fix USP0008 with partial types

---

src/Microsoft.Unity.Analyzers/DiagnosticCategory.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx

Fixes #297 
Given diagnostic categories are used for bulk enabling/disabling analyzers like in `.editorconfig` files, keep technical names without exposing them through resources.

Do not expose categories through resources

---

src/Microsoft.Unity.Analyzers.Tests/ProtectedUnityMessageTests.cs
src/Microsoft.Unity.Analyzers/ProtectedUnityMessage.cs

Found while investigating #308 
Fix trivia handling with UNT0021, when using messages without modifiers

Fix trivia handling with UNT0021, when using messages without modifiers

---

src/Microsoft.Unity.Analyzers/BasePositionAndRotation.cs
src/Microsoft.Unity.Analyzers/BaseVectorConversion.cs
src/Microsoft.Unity.Analyzers/CreateInstance.cs
src/Microsoft.Unity.Analyzers/DestroyTransform.cs
src/Microsoft.Unity.Analyzers/EmptyUnityMessage.cs
src/Microsoft.Unity.Analyzers/ImproperMenuItemMethod.cs
src/Microsoft.Unity.Analyzers/ImproperMessageCase.cs
src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs
src/Microsoft.Unity.Analyzers/IndirectionMessage.cs
src/Microsoft.Unity.Analyzers/InitializeOnLoadStaticCtor.cs
src/Microsoft.Unity.Analyzers/InputGetKey.cs
src/Microsoft.Unity.Analyzers/LoadAttributeMethod.cs
src/Microsoft.Unity.Analyzers/MessageSignature.cs
src/Microsoft.Unity.Analyzers/MethodInvocation.cs
src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs
src/Microsoft.Unity.Analyzers/PropertyDrawerOnGUI.cs
src/Microsoft.Unity.Analyzers/ProtectedUnityMessage.cs
src/Microsoft.Unity.Analyzers/TagComparison.cs
src/Microsoft.Unity.Analyzers/TryGetComponent.cs
src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs
src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs
src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs
src/Microsoft.Unity.Analyzers/VectorMath.cs

Fixes #308 
Fix BatchFixer for UNT0021 (and audit/fix for others)
We are using the default BatchFixer provided by Roslyn.
See the documentation here:
https://github.com/dotnet/roslyn/blob/main/docs/analyzers/FixAllProvider.md
We were wrongly setting the **Equivalence Key**: A string value representing an equivalence class of all code actions registered by a code fixer or refactoring. Two code actions are treated as equivalent if they have equal EquivalenceKey values and were generated by the same code fixer or refactoring.

Fix BatchFixer

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Starting February 1, 2024 the default token access for the `GITHUB_TOKEN`, which is used for all GitHub Actions workflows, will be changing from Read/Write to Read-only for its default access. You will need to make [adjustments to your workflows](https://docs.opensource.microsoft.com/github/apps/permission-changes/#what-steps-must-i-take-to-avoid-a-bad-time) by adding a permissions block and detailing the levels of access to the [required scopes](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#permissions) . Failure to make adjustments to your workflows will break your workflows that require any permission above Read.
See https://docs.opensource.microsoft.com/github/apps/permission-changes/

Fix workflows

---

doc/USP0022.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs

Fixes #323
- IDE0270 is suppressed by the UnityObjectNullHandlingAnalyzer
- UnityObjectNullHandlingAnalyzer now supresses IDE0270

Add USP0022, UnityObjectIfNullCoalescingSuppressor

---

src/Microsoft.Unity.Analyzers.Tests/TryGetComponentTests.cs
src/Microsoft.Unity.Analyzers/TryGetComponent.cs

Simplify UNT0026 scope by only supporting variable declaration constructs. Current implementation with assignments can lead to unexpected code flows. 
Especially when the relevance of this diagnostic is debated #290 
Fixes #334

Simplify UNT0026, only support variable declaration constructs

---

.config/dotnet-tools.json
.husky/pre-commit
.husky/task-runner.json
src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj

Format staged C# files on commit

Format staged C# files on commit

---

src/Microsoft.Unity.Analyzers.Tests/MessageSignatureTests.cs
src/Microsoft.Unity.Analyzers/CodeFixContextExtensions.cs
src/Microsoft.Unity.Analyzers/MessageSignature.cs

Fixes #362
Fix UNT0006 when a Unity message is wrongly referenced.

Fix UNT0006 when a Unity message is wrongly referenced.

---

src/Microsoft.Unity.Analyzers.Tests/SerializeFieldSuppressorTests.cs
src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #371 
Add support for `CreateProperty`

Add support for CreateAttribute

---

src/Directory.Packages.props
src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj

Bump Roslyn to 4.13

---

doc/UNT0002.md

Fixes #378
There was double double-quote in string for a 6 years old doc file that's been still being linked in Visual Studio.
- make them single double-quote `"` in both end of the string

Fix syntax issue in UNT0002.md

---

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerVerificationContext.cs

Those test-wide filters are not needed anymore with Unity 6

Remove legacy filters

---

doc/UNT0039.md
doc/index.md
src/Microsoft.Unity.Analyzers.Tests/CacheYieldInstructionAnalyzerTests.cs
src/Microsoft.Unity.Analyzers.Tests/RequireComponentTests.cs
src/Microsoft.Unity.Analyzers/BaseGetComponentAnalyzer.cs
src/Microsoft.Unity.Analyzers/CacheYieldInstructionAnalyzer.cs
src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs
src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs
src/Microsoft.Unity.Analyzers/RequireComponent.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs
src/Microsoft.Unity.Analyzers/Resources/Strings.resx
src/Microsoft.Unity.Analyzers/TryGetComponent.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs
src/new-analyzer/AnalyzerCodeFixDiagnosticBuilder.cs

Fixes #35 
UNT0039 Use `RequireComponent` attribute when self-invoking `GetComponent`

UNT0039 Use `RequireComponent` attribute when self-invoking `GetComponent`

---

src/Microsoft.Unity.Analyzers/TypeSymbolExtensions.cs
src/Microsoft.Unity.Analyzers/UnityStubs.cs

Fixes #410 
Add support for `UniTask` for Unity messages, similarly to what we've done for the built-in `Awaitable`.
`UniTask` users where forced to suppress `UNT0006`:
https://github.com/YARC-Official/YARG/blob/0050bf60b7f87a4fb10faf0d96be49e9549b40d8/Assets/Script/Gameplay/BackgroundManager.cs#L46
Note: we have to review/sync IDE-side message detection as well.

Add support for UniTask
