src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fix Editor.CreateInspectorGUI() scope.
See https://docs.unity3d.com/2019.1/Documentation/ScriptReference/Editor.CreateInspectorGUI.html
- [x ] I have read the [Contribution Guide](/CONTRIBUTING.md) ;
=> Editor.CreateInspectorGUI() is public

src/new-analyzer/Program.cs
=> Update the scaffolder with the new test infrastructure

src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs, src/Microsoft.Unity.Analyzers/KnownMethods.cs, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/Microsoft.Unity.Analyzers/TagComparison.cs, src/Microsoft.Unity.Analyzers/UnityStubs.cs
Introduce a helper type to remove code and data duplication.
Use strongly type names instead of inline strings.
=> Introduce KnownMethods to remove duplication

src/Microsoft.Unity.Analyzers.Tests/BaseTest.cs, src/Microsoft.Unity.Analyzers.Tests/ConsistencyTests.cs, src/Microsoft.Unity.Analyzers.Tests/ContextMenuSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/CreateInstanceTests.cs, src/Microsoft.Unity.Analyzers.Tests/EmptyUnityMessageTests.cs, src/Microsoft.Unity.Analyzers.Tests/GetComponentIncorrectTypeTests.cs, src/Microsoft.Unity.Analyzers.Tests/ImproperSerializeFieldTests.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/InitializeOnLoadStaticCtorTests.cs, src/Microsoft.Unity.Analyzers.Tests/MessageSignatureTests.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers.Tests/NonGenericGetComponentTests.cs, src/Microsoft.Unity.Analyzers.Tests/SerializeFieldSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/TagComparisonTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnusedCoroutineReturnValueTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnusedMessageSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnusedMethodSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/UpdateDeltaTimeTests.cs, src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj, src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs
suppressor ;
Proper async rewrite for the test infrastructure.
Use those analyzers to check that we are doing things the right way:
https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/index.md
=> Proper async rewrite for the test infrastructure

src/Microsoft.Unity.Analyzers.Tests/ImproperSerializeFieldTests.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx
Removes unnecessary allocations in ImproperSerializeField.
=> Remove unecessary allocations in ImproperSerializeField

src/new-analyzer/AnalyzerCodeFixDiagnosticBuilder.cs, src/new-analyzer/SuppressorDiagnosticBuilder.cs
We moved to async testing without updating scaffolding code
=> We moved to async testing without updating scaffolding code

src/Microsoft.Unity.Analyzers/ContextMenuSuppressor.cs, src/Microsoft.Unity.Analyzers/CreateInstance.cs, src/Microsoft.Unity.Analyzers/EmptyUnityMessage.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadMethod.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadStaticCtor.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/Microsoft.Unity.Analyzers/SetPixelsMethodUsage.cs, src/Microsoft.Unity.Analyzers/TagComparison.cs, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs, src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs, src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs
Audit possible NRE candidates and fix them
=> Audit remaining NRE candidates

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, src/Microsoft.Unity.Analyzers/UnityStubs.cs
=> Bump Stubs and test infrastructure to Unity 2019.4 LTS

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticLocation.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticResult.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers.Tests/UnityPath.cs
Review of the test infrastructure
=> Review test infrastructure

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2019.4.1f1

src/Microsoft.Unity.Analyzers/Directory.Build.props
Technical update, only used when building signed bits outside the Github infrastructure.
=> Import MicroBuild explicitly

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs
Add support for configurable editorconfig and replace old NoWarn system.
=> Add configurable editorconfig support to the test infrastructure

doc/UNT0018.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/ReflectionTests.cs, src/Microsoft.Unity.Analyzers/Reflection.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx
Fixes #83 
Add USP0018 analyzer for checking System.Reflection features in performance critical messages
=> Add USP0018 for checking System.Reflection features in performance critical messages

src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fixes #113
Audit all monobehaviours messages for coroutine compatibility.
=> Update stubs compatible with Unity coroutines

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fixes #118 
Fix AssetPostprocessor stub signatures
=> Fix OnAssignMaterialModel return type

src/Microsoft.Unity.Analyzers/UnityStubs.cs
Update stubs with recent 2019.4 LTS
=> Stubs 2019.4

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2019.4.16f1

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerVerificationContext.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticResult.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/NullableReferenceTypesSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/SerializeFieldSuppressorTests.cs
Provide a way to access analyzer options
=> Better control for analyzer options

src/Microsoft.Unity.Analyzers.Tests/ContextMenuSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/CreateInstanceTests.cs, src/Microsoft.Unity.Analyzers.Tests/ImproperMenuItemMethodTests.cs, src/Microsoft.Unity.Analyzers.Tests/IndirectionMessageTests.cs
=> Tests review

src/Microsoft.Unity.Analyzers.Tests/CreateInstanceTests.cs, src/Microsoft.Unity.Analyzers.Tests/EmptyUnityMessageTests.cs, src/Microsoft.Unity.Analyzers.Tests/ImproperMenuItemMethodTests.cs, src/Microsoft.Unity.Analyzers.Tests/ImproperSerializeFieldTests.cs, src/Microsoft.Unity.Analyzers.Tests/IndirectionMessageTests.cs, src/Microsoft.Unity.Analyzers.Tests/InitializeOnLoadMethodTests.cs, src/Microsoft.Unity.Analyzers.Tests/MethodInvocationDirectCallTests.cs, src/Microsoft.Unity.Analyzers.Tests/MethodInvocationNameOfTests.cs, src/Microsoft.Unity.Analyzers.Tests/NonGenericGetComponentTests.cs, src/Microsoft.Unity.Analyzers.Tests/ProtectedUnityMessageTests.cs, src/Microsoft.Unity.Analyzers.Tests/SetPositionAndRotationTests.cs, src/Microsoft.Unity.Analyzers.Tests/TagComparisonTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingTests.cs, src/Microsoft.Unity.Analyzers.Tests/UpdateDeltaTimeTests.cs, src/Microsoft.Unity.Analyzers/ImproperMenuItemMethod.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadMethod.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs, src/Microsoft.Unity.Analyzers/ProtectedUnityMessage.cs, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs
Fixes #140 
Audit of all calls to `VerifyCSharpFixAsync`
Better comment handling when applying codefixes
=> Better comment handling when applying codefixes

doc/UNT0008.md, doc/UNT0023.md, doc/USP0001.md, doc/USP0002.md, doc/USP0017.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingTests.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs
Fixes #70 
Coalescing assignment Analyzer/Suppressor/CodeFix
=> Coalescing assignment Analyzer/Suppressor/CodeFix

src/Microsoft.Unity.Analyzers.Tests/SetPositionAndRotationTests.cs, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs
Fixes #144 
Fixes #145 
Fix `UNT0022` issues
=> Fix UNT0022 issues

src/Microsoft.Unity.Analyzers.Tests/CreateInstanceTests.cs, src/Microsoft.Unity.Analyzers.Tests/IndirectionMessageTests.cs, src/Microsoft.Unity.Analyzers.Tests/MethodInvocationDirectCallTests.cs, src/Microsoft.Unity.Analyzers.Tests/MethodInvocationNameOfTests.cs, src/Microsoft.Unity.Analyzers.Tests/NonGenericGetComponentTests.cs, src/Microsoft.Unity.Analyzers/CodeFixContextExtensions.cs, src/Microsoft.Unity.Analyzers/CreateInstance.cs, src/Microsoft.Unity.Analyzers/EmptyUnityMessage.cs, src/Microsoft.Unity.Analyzers/ImproperMenuItemMethod.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/IndirectionMessage.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadMethod.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadStaticCtor.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/Microsoft.Unity.Analyzers/ProtectedUnityMessage.cs, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/TagComparison.cs, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs, src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs, src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs
Fixes #147 
Fix `UNT0019` issues, and audit/refactor all codefixes. 
Note we should do probably the same work for all suppressors, given we already had a similar issue: #88
=> Fix UNT0019 issues

src/Microsoft.Unity.Analyzers/ContextMenuSuppressor.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadMethodSuppressor.cs, src/Microsoft.Unity.Analyzers/MessageSuppressor.cs, src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs, src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs, src/Microsoft.Unity.Analyzers/SuppressionAnalysisContextExtensions.cs, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs, src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs
Apply the same refactoring to suppressors that we did for codefixes in #148
=> Apply the same refactoring to suppressors that we did for codefixes

src/Microsoft.Unity.Analyzers.Tests/BaseTest.cs, src/Microsoft.Unity.Analyzers.Tests/SerializeFieldSuppressorTests.cs, src/Microsoft.Unity.Analyzers/CreateInstance.cs, src/Microsoft.Unity.Analyzers/IndirectionMessage.cs, src/Microsoft.Unity.Analyzers/KnownMethods.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs, src/Microsoft.Unity.Analyzers/ScriptInfo.cs, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/UnityStubs.cs, src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs, src/new-analyzer/AbstractDiagnosticBuilder.cs
=> Code gardening

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingTests.cs, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs
Fix invalid cast with Null Propagation QuickFix
=> Fix invalid cast with Null Propagation QuickFix

src/Microsoft.Unity.Analyzers/CodeFixContextExtensions.cs, src/Microsoft.Unity.Analyzers/CreateInstance.cs, src/Microsoft.Unity.Analyzers/GetComponentIncorrectType.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadMethod.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs, src/Microsoft.Unity.Analyzers/MethodUsage.cs, src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/Microsoft.Unity.Analyzers/Nullability.cs, src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs, src/Microsoft.Unity.Analyzers/ScriptInfo.cs, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/SuppressionAnalysisContextExtensions.cs, src/Microsoft.Unity.Analyzers/TagComparison.cs, src/Microsoft.Unity.Analyzers/TypeSymbolExtensions.cs, src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs, src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs
Enable nullable reference types for nullability checking.
=> Enable nullable reference types

src/new-analyzer/AnalyzerCodeFixDiagnosticBuilder.cs, src/new-analyzer/SuppressorDiagnosticBuilder.cs
Update generation code with newer test API.
=> Use proper API for generated code

src/Microsoft.Unity.Analyzers.Tests/BaseTest.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs
Fixes #164 
Fix exception with explicit interface method implementations when using QuickFix
Filter methods with an `ExplicitInterfaceSpecifier` set.
=> Fix exception with explicit interface method implementations

doc/UNT0013.md, src/Microsoft.Unity.Analyzers.Tests/ImproperSerializeFieldTests.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs
Fixes #166
Add static and readonly fields to the detected patterns
Upgrade analyzer, tests and documentation
=> Upgade UNT0013 to detect static and readonly fields

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2020.3.9f1

src/Microsoft.Unity.Analyzers/UnityStubs.cs
=> Port 2020.3.9f1 updates

src/Microsoft.Unity.Analyzers/ContextMenuSuppressor.cs, src/Microsoft.Unity.Analyzers/MessageBuilder.cs, src/Microsoft.Unity.Analyzers/ScriptInfo.cs, src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs
Quick pass at removing some of our allocations in the analyzers when possible.
=> Avoid allocations in the analyzers when possible

src/Microsoft.Unity.Analyzers.Tests/VectorMathTests.cs, src/Microsoft.Unity.Analyzers/VectorMath.cs
Fixes #178 
Fix supported expression detection with UNT0024
=> Fix supported expression detection with UNT0024

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2020.3.18f1

doc/UNT0016.md, src/Microsoft.Unity.Analyzers.Tests/MethodInvocationNameOfTests.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs
Fixes #181 
Add `CancelInvoke` support to UNT0016 
See two overloads: https://docs.unity3d.com/ScriptReference/MonoBehaviour.CancelInvoke.html
=> Add CancelInvoke support to UNT0016

src/Microsoft.Unity.Analyzers/UnityStubs.cs
Refactor stubs and add missing AssetPostprocessor methods
=> Refactor stubs and add missing AssetPostprocessor methods

src/Microsoft.Unity.Analyzers.Tests/Directory.Build.props, src/Microsoft.Unity.Analyzers/Directory.Build.targets
=> [internal] ns20

src/Microsoft.Unity.Analyzers.Tests/ConsistencyTests.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj
Bump dev dependencies only (we still targe Roslyn 3.4.0 for the main analyzer assembly)
=> Bump dev dependencies

src/Microsoft.Unity.Analyzers/Directory.Build.props
Move to Microsoft.VisualStudioEng.MicroBuild.Core
=> [internal] Move to Microsoft.VisualStudioEng.MicroBuild.Core

src/Microsoft.Unity.Analyzers.Tests/MessageSignatureTests.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs
Fixes #182 
Fix Instance/Static method detection when checking signatures
=> Fix UNT0006 Instance/Static detection

doc/UNT0003.md, doc/UNT0014.md, doc/UNT0026.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/GetComponentIncorrectTypeTests.cs, src/Microsoft.Unity.Analyzers.Tests/NonGenericGetComponentTests.cs, src/Microsoft.Unity.Analyzers.Tests/TryGetComponentTests.cs, src/Microsoft.Unity.Analyzers/KnownMethods.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/SyntaxNodeExtensions.cs, src/Microsoft.Unity.Analyzers/TryGetComponent.cs, src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fixes #76 
- Add TryGetComponent quick fix and diagnostic
- Updated `UNT0003`, usage of non generic `GetComponent`, to work with `TryGetComponent` as well.
- Updated `UNT0014`, `GetComponent` called with non component/interface, to work with `TryGetComponent` as well.
=> Add TryGetComponent quick fix and diagnostic

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
Enable Github's CodeQL support
Dashboard: https://github.com/microsoft/Microsoft.Unity.Analyzers/security/code-scanning
=> Enable CodeQL scanning

src/Microsoft.Unity.Analyzers.Tests/ConsistencyTests.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticResult.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers.Tests/UnityPath.cs, src/new-analyzer/AbstractDiagnosticBuilder.cs, src/new-analyzer/Program.cs, src/new-analyzer/new-analyzer.csproj
Enable Nullable support in all projects
=> Enable Nullable support in all projects

doc/UNT0015.md, doc/USP0012.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/LoadAttributeMethodSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/LoadAttributeMethodTests.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethodSuppressor.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fixes #212 
Update both the existing `UNT0015` analyzer and `USP0012` suppressor to add support for `DidReloadScripts`
=> Add support for `DidReloadScripts` attribute.

doc/USP0019.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/ImplicitUsageAttributeSuppressorTests.cs, src/Microsoft.Unity.Analyzers/ImplicitUsageAttributeSuppressor.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fixes #212 
Add USP0019 with tests and docs.
=> Add USP0019 Don't flag private methods decorated with `PreserveAttribute` or `UsedImplicitlyAttribute` as unused

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> Move to CodeQL v2

src/new-analyzer/AbstractDiagnosticBuilder.cs, src/new-analyzer/AnalyzerCodeFixDiagnosticBuilder.cs
Use file scoped namespaces for templates
=> Use file scoped namespaces for templates

src/Microsoft.Unity.Analyzers/ContextMenuSuppressor.cs, src/Microsoft.Unity.Analyzers/CreateInstance.cs, src/Microsoft.Unity.Analyzers/EmptyUnityMessage.cs, src/Microsoft.Unity.Analyzers/ImplicitUsageAttributeSuppressor.cs, src/Microsoft.Unity.Analyzers/ImproperMenuItemMethod.cs, src/Microsoft.Unity.Analyzers/ImproperSerializeField.cs, src/Microsoft.Unity.Analyzers/IndirectionMessage.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadStaticCtor.cs, src/Microsoft.Unity.Analyzers/InputGetKey.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethodSuppressor.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs, src/Microsoft.Unity.Analyzers/MessageSuppressor.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs, src/Microsoft.Unity.Analyzers/PhysicsAllocMethodUsage.cs, src/Microsoft.Unity.Analyzers/PropertyDrawerOnGUI.cs, src/Microsoft.Unity.Analyzers/ProtectedUnityMessage.cs, src/Microsoft.Unity.Analyzers/Reflection.cs, src/Microsoft.Unity.Analyzers/SerializeFieldSuppressor.cs, src/Microsoft.Unity.Analyzers/SetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/SuppressionAnalysisContextExtensions.cs, src/Microsoft.Unity.Analyzers/TagComparison.cs, src/Microsoft.Unity.Analyzers/ThrowExpressionSuppressor.cs, src/Microsoft.Unity.Analyzers/TryGetComponent.cs, src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs, src/Microsoft.Unity.Analyzers/UnusedMethodSuppressor.cs, src/Microsoft.Unity.Analyzers/UpdateDeltaTime.cs, src/Microsoft.Unity.Analyzers/VectorMath.cs
Fix all nullability warnings after Roslyn 3.7.0 bump
=> Fix all nullability warnings after Roslyn 3.7.0 bump

doc/UNT0030.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/DestroyTransformTests.cs, src/Microsoft.Unity.Analyzers/DestroyTransform.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx
Fixes #226 
Add UNT0030, Calling `Destroy` or `DestroyImmediate` on a `Transform`
=> Add UNT0030, Calling `Destroy` or `DestroyImmediate` on a `Transform`

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2021.3.7f1 LTS

doc/UNT0031.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/AssetOperationInLoadAttributeMethodTests.cs, src/Microsoft.Unity.Analyzers/AssetOperationInLoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/InitializeOnLoadStaticCtor.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/UnityStubs.cs
Fixes #238 
Add UNT0031 Asset operations in LoadAttribute method
=> Add UNT0031 Asset operations in LoadAttribute method

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2021.3.9f1

src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj
=> Bump dependencies

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, doc/UNT0032.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/SetLocalPositionAndRotationTests.cs, src/Microsoft.Unity.Analyzers/BaseSetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/SetLocalPositionAndRotation.cs
Fixes #244 
Add UNT0032: Inefficient method to set localPosition and localRotation
=> Add UNT0032: Inefficient method to set localPosition and localRotation

src/Microsoft.Unity.Analyzers.Tests/TryGetComponentTests.cs, src/Microsoft.Unity.Analyzers/TryGetComponent.cs
Fixes #248 
Fixes inline ifs with UNT0026
=> Fix inline ifs with UNT0026

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, README.md, src/Microsoft.Unity.Analyzers.Tests/ConsistencyTests.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/CodeFixVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticResult.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers/BaseSetPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/DestroyTransform.cs, src/Microsoft.Unity.Analyzers/ImplicitUsageAttributeSuppressor.cs, src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj
Now that .NET 7 is GA, Build analyzers tests with it and bump Language version to C# 11.0
=> Build analyzer tests with net7, bump Language version to C# 11.0

doc/UNT0033.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/ImproperMessageCaseTests.cs, src/Microsoft.Unity.Analyzers/EmptyUnityMessage.cs, src/Microsoft.Unity.Analyzers/ImproperMessageCase.cs, src/Microsoft.Unity.Analyzers/MethodDeclarationExtensions.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx
Fixes #251 
Add `UNT0033` Incorrect message case
=> Add `UNT0033` Incorrect message case

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers/ImproperMessageCase.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs
Promote `UNT0033`, `UNT0015` and `UNT0006` from `Info` to `Warning` severity.
=> Promote `UNT0033`, `UNT0015` and `UNT0006` from `Info` to `Warning` severity.

.github/workflows/ci-windows.yml
CodeQL now supports Windows 11
=> CodeQL now supports Windows 11

.github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml
=> Bump Unity to 2021.3.16f1

.github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, README.md, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/UnityPath.cs
Rework Hub/Standalone installations discovery, and add Linux pipeline
=> Rework discovery and add linux pipeline

src/Microsoft.Unity.Analyzers.Tests/ImproperMessageCaseTests.cs, src/Microsoft.Unity.Analyzers/ImproperMessageCase.cs
Fixes #262 
Fix false positives with overloads
=> Fix UNT0033 detection with overloads

.github/workflows/ci-linux.yml
=> Fix Linux cache

doc/USP0020.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/MessageSuppressorTests.cs, src/Microsoft.Unity.Analyzers/MessageSuppressor.cs
Fixes [#10298781](https://developercommunity.visualstudio.com/t/Unity-Message-functions-Start-Update-/10298781)
Suppress IDE0052 on Unity messages
=> Add USP0020 - The Unity runtime invokes Unity messages

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
=> Bump test/dev dependencies

doc/UNT0034.md, doc/UNT0035.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/Vector2ConversionTests.cs, src/Microsoft.Unity.Analyzers.Tests/Vector3ConversionTests.cs, src/Microsoft.Unity.Analyzers/BaseVectorConversion.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/Vector2Conversion.cs, src/Microsoft.Unity.Analyzers/Vector3Conversion.cs
Vector2<=>Vector3 conversions with `UNT0034` and `UNT0035`
=> Vector2<=>Vector3 conversions with `UNT0034` and `UNT0035`

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
=> Bump packages

doc/USP0021.md, doc/index.md, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.Designer.cs, src/Microsoft.Unity.Analyzers/Resources/Strings.resx, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs
Fixes #291 
Add `UNT0021` Prefer reference equality
=> Add `UNT0021` Prefer reference equality

src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticLocation.cs, src/Microsoft.Unity.Analyzers/MessageBuilder.cs, src/Microsoft.Unity.Analyzers/Microsoft.Unity.Analyzers.csproj, src/Microsoft.Unity.Analyzers/Nullability.cs, src/Microsoft.Unity.Analyzers/ScriptInfo.cs, src/Microsoft.Unity.Analyzers/TryGetComponent.cs, src/Microsoft.Unity.Analyzers/VectorMath.cs
=> Use C# 12 for analyzers assembly

src/Microsoft.Unity.Analyzers.Tests/Vector2ConversionTests.cs, src/Microsoft.Unity.Analyzers.Tests/Vector3ConversionTests.cs, src/Microsoft.Unity.Analyzers/BaseVectorConversion.cs
Fix UNT0034 and UNT0035 with ambiguous overloads
=> Fix UNT0034 and UNT0035 with ambiguous overloads

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/ConsistencyTests.cs
=> Bump xUnit

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerVerificationContext.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers/MethodUsage.cs, src/Microsoft.Unity.Analyzers/PhysicsAllocMethodUsage.cs
Bump packages and code-gardening
=> Bump packages and code-gardening

src/Microsoft.Unity.Analyzers.Tests/AssetOperationInLoadAttributeMethodTests.cs, src/Microsoft.Unity.Analyzers.Tests/DestroyTransformTests.cs, src/Microsoft.Unity.Analyzers.Tests/GetLocalPositionAndRotationTests.cs, src/Microsoft.Unity.Analyzers.Tests/ImproperMessageCaseTests.cs, src/Microsoft.Unity.Analyzers.Tests/LoadAttributeMethodTests.cs, src/Microsoft.Unity.Analyzers.Tests/MessageSignatureTests.cs, src/Microsoft.Unity.Analyzers.Tests/NonGenericGetComponentTests.cs, src/Microsoft.Unity.Analyzers.Tests/NullableReferenceTypesSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/PhysicsAllocMethodUsageTests.cs, src/Microsoft.Unity.Analyzers.Tests/SetLocalPositionAndRotationTests.cs, src/Microsoft.Unity.Analyzers.Tests/SetPositionAndRotationTests.cs, src/Microsoft.Unity.Analyzers.Tests/ThrowExpressionSuppressorTests.cs, src/Microsoft.Unity.Analyzers.Tests/TryGetComponentTests.cs, src/Microsoft.Unity.Analyzers.Tests/UnityObjectNullHandlingSuppressorTests.cs, src/Microsoft.Unity.Analyzers/Directory.Build.props, src/Microsoft.Unity.Analyzers/Directory.Build.targets, src/Microsoft.Unity.Analyzers/ImproperMessageCase.cs, src/Microsoft.Unity.Analyzers/MessageSignature.cs, src/Microsoft.Unity.Analyzers/MethodInvocation.cs, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs, src/Microsoft.Unity.Analyzers/PropertyDrawerOnGUI.cs, src/Microsoft.Unity.Analyzers/ProtectedUnityMessage.cs, src/Microsoft.Unity.Analyzers/SetLocalPositionAndRotation.cs, src/Microsoft.Unity.Analyzers/ThrowExpressionSuppressor.cs, src/Microsoft.Unity.Analyzers/TryGetComponent.cs, src/Microsoft.Unity.Analyzers/UnityObjectNullHandling.cs, src/Microsoft.Unity.Analyzers/UnusedCoroutineReturnValue.cs
=> Code cleanup

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
=> Bump Roslyn packages

src/Directory.Packages.props
=> Bump test packages

.github/workflows/ci-linux.yml, .github/workflows/ci-macos.yml, .github/workflows/ci-windows.yml, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/DiagnosticVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/VectorMathTests.cs, src/Microsoft.Unity.Analyzers/UnityStubs.cs, src/Microsoft.Unity.Analyzers/VectorMath.cs
Fixes #288
Improve `UNT0024` to support Unity.Mathematics floatX types
- analyzer is already compatible (we just need to add new suported types)
- improve test assembly loader (we need to reference `Unity.Mathematics`)
- improve tests to support new types
=> Improve UNT0024 to support Unity.Mathematics floatX types

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Vsix/Microsoft.Unity.Analyzers.Vsix.csproj
Migrate VSIX project to SDK Style
=> Migrate VSIX project to SDK Style

doc/UNT0016.md
Fixes #
A spelling mistake.
-
-
-
=> Correct spelling mistake in UNT0016.md

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
=> Bump Roslyn to 4.10

src/Microsoft.Unity.Analyzers.Tests/VectorMathTests.cs, src/Microsoft.Unity.Analyzers/AssetOperationInLoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/BaseGetPositionAndRotationContext.cs, src/Microsoft.Unity.Analyzers/BasePositionAndRotation.cs, src/Microsoft.Unity.Analyzers/BaseVectorConversion.cs, src/Microsoft.Unity.Analyzers/LoadAttributeMethod.cs, src/Microsoft.Unity.Analyzers/MethodDeclarationExtensions.cs, src/Microsoft.Unity.Analyzers/NullableReferenceTypesSuppressor.cs, src/Microsoft.Unity.Analyzers/TagComparison.cs, src/Microsoft.Unity.Analyzers/TryGetComponent.cs, src/Microsoft.Unity.Analyzers/TypeSymbolExtensions.cs, src/Microsoft.Unity.Analyzers/UnityStubs.cs, src/Microsoft.Unity.Analyzers/VectorMath.cs
=> Re-format codebase

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers.Tests/NullableReferenceTypesSuppressorTests.cs
=> Bump to Roslyn 4.11

.github/workflows/ci-matrix.yml, README.md, src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/SuppressorVerifier.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj, src/Microsoft.Unity.Analyzers/NonGenericGetComponent.cs, src/new-analyzer/new-analyzer.csproj
Bump .NET to 9, and use NetAnalyzers from the current SDK instead of using a nuget package.
=> Bump .NET to 9.

.config/dotnet-tools.json
=> Bump Husky

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Infrastructure/AnalyzerOptionsProvider.cs, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
=> Bump Roslyn to 4.12

src/Directory.Packages.props, src/nuget.config
Move to the nuget.org feed, and properly update dependencies
We are using the exact same `nuget.config` as https://github.com/microsoft/PowerToys (114k stars)
=> Move to the nuget.org feed, and properly update dependencies

src/Microsoft.Unity.Analyzers.Tests/Directory.Build.props, src/Microsoft.Unity.Analyzers/Directory.Build.props
Remove unused `DebugRelease` configuration.
=> Remove DebugRelease Configuration

src/Directory.Packages.props, src/Microsoft.Unity.Analyzers.Tests/Microsoft.Unity.Analyzers.Tests.csproj
=> Remove unused nuget

.husky/pre-commit
Do not run linter when merging or rebasing
=> Do not run linter when merging or rebasing
